# Generated by Django 4.2.1 on 2023-05-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='pk')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('url', models.URLField(blank=True, default='', max_length=512, verbose_name='url')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('document', 'document'), ('binary', 'binary'), ('compressed', 'compressed'), ('other', 'other')], max_length=255)),
                ('size', models.PositiveBigIntegerField(blank=True, db_comment='storage size, unit: B', default=0, verbose_name='size/B')),
                ('duration', models.BigIntegerField(blank=True, db_comment='duration of media, unit: ms', default=0, verbose_name='duration/ms')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
